name: C++ Unit Tests

on:
  push:
    branches:
      - main
  pull_request:
    paths:
      - 'src/cppsrc/**'
    branches:
      - '**'

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install --upgrade pipx
          pipx install cmake ninja conan poetry clang-tidy clang-format

      - name: Profile detect
        run: |
          conan profile detect

      - name: Run C++ Unit Tests
        run: make test_cpp
