name: C++ Unit Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - '**'

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      # Check out the repository
      - name: Checkout repository code
        uses: actions/checkout@v3

      # Install build tools
      - name: Install build dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential

      # Run Make to build the project
      - name: Build the project
        run: make

      # Run Make to execute unit tests
      - name: Run C++ unit tests
        run: make test
