name: C++ Linting and Formatting

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - '**'

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Python Set Up
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      
      - name: Install tools
        run: |
          pip install --upgrade pip
          pip install --upgrade pipx
          pipx install cmake ninja conan poetry clang-tidy clang-format

      - name: Profile detect
        run: |
          conan profile detect

      - name: Run linter and formatter checks
        run: |
          make lint_format_check_cpp

