name: Integration Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - '**'

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Python Set Up
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      
      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install --upgrade pipx
          pipx install cmake ninja conan poetry clang-tidy clang-format

      - name: Profile detect 
        run: |
          conan profile detect

      - name: Run tests
        run: |
          make test_int