name: Python Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - '**'

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      # Set up Python environment (you can specify your version)
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'  # Use a version that is suitable for your project

      # Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest  # Install pytest
          pip install -r requirements.txt  # Install other dependencies from your requirements file (if any)

      # Run Pytest
      - name: Run tests with pytest
        run: |
          pytest --maxfail=1 --disable-warnings -q
