name: Python Linting and Type Checking

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - '**'

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Python Set Up
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install tools
        run: |
          pip install --upgrade pip
          pip install --upgrade pipx
          pipx install poetry conan ninja mypy ruff
          poetry add requests
          python3 -m pip install types-requests
          

      - name: Profile detect 
        run: |
          conan profile detect
      
      - name: Run
        run: |
          make lint_py
